# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2018-10-21 08:02:45,010] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.5025


In [8]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[1.59111901e-01 1.29410760e-02 7.59487612e-03 7.23551412e-03]
 [1.40592850e-03 8.85163847e-04 1.87351070e-03 7.47811159e-02]
 [9.16151778e-04 6.52348001e-02 3.76225562e-03 5.24133411e-03]
 [2.44156130e-04 1.22260401e-03 2.48039087e-04 6.80383219e-02]
 [2.80341267e-01 1.78772211e-04 4.99816900e-03 1.83919630e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.61165213e-05 1.47159059e-04 1.05213825e-02 1.12680803e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.24101523e-03 2.64340189e-04 3.41948608e-04 3.53744126e-01]
 [0.00000000e+00 3.73437025e-01 0.00000000e+00 0.00000000e+00]
 [5.04247090e-02 0.00000000e+00 3.41493555e-04 2.68861841e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.31060986e-03 6.00902959e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.88315363e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.